### PR TITLE
v5.2.0 Update

### PR DESCRIPTION
**Pull request by DuckBoss**
## Core Updates

- global_aliases.csv file renamed to custom_aliases.csv and works similarly to the new custom permissions implementation
- custom_permissions.csv file implemented (auto-generated if missing)
- custom_user_privileges.csv file implemented (auto-generated if missing)
- Added `!getpermission <command_name>` command to display the current permission requirement for a command
- Added `!setpermission <command_name> <permission_level>` command to change specific command permissions
- Added `!refreshpermissions` command to update command permissions from the custom_permissions.csv file
- Added `!refreshaliases` command to update custom aliases from the custom_aliases.csv file
- Added `!refreshuserprivileges` command to update user privileges from the custom_user_privileges.csv file
- Added new launch parameter: `-regeneratedatabase`
This launch parameter deletes the existing internal database if it exists, so that it can be regenerated from scratch.
- Database integrity checking, which only regenerates the aliases/commands like it used to when plugin data has been modified or the bot version has been updated. This would prevent data conflicts and other issues when updating the bots. This can be disabled in the `config.ini` file or with launch parameters: `disableintegritycheck`
- Aliases/user privileges/command permissions can be imported from a remote URL using the `!importaliases/!importuserprivileges/!importpermissions` commands.

### Misc Updates

- Optimized logging and debugging messages in the database library.
- Removed redundant aliases in `custom_aliases.csv` file (formally called `global_aliases.csv`)
- Added alias `!changepermission` for the new command `!setpermission`
- Updated command denial message for blacklisted users.
- Refactored user privilege checks.
- Fixed error-handling for the `!volume` command.
- Optimized imports in some library functions.
- A warning is now given if database backups are enabled but the database is missing

### CODE REVIEW

**Comment by benwallacestock** [comment]
I have jsut given this a quick test and I can confirm that loading the permissions out of the `custom_permissions.csv` file using the command works perfectly.

Thanks so much I cant wait for it to get merged in and start playing!

**Comment by DuckBoss** [comment]
> I have jsut given this a quick test and I can confirm that loading the permissions out of the `custom_permissions.csv` file using the command works perfectly.
> 
> Thanks so much I cant wait for it to get merged in and start playing!

That's great to hear! I have already merged it to the master branch, but I need to update some documentation before a release build.

**Comment by DuckBoss** [comment]
Hello @benwallacestock , just wanted to give you an update. I'm planning on creating the v5.2.0 release tomorrow (Sunday) with a couple additional features like config file integrity checking and an overhauled wiki website.

**Comment by benwallacestock** [comment]
Sounds good! I was giving a test yesterday and I'm not share if it is an issue but, after restarting the bot it did not read the permissions from the file, and I had to re run the refreshpermissions command. Not a big issue as it will rarely be restarted but it sounds like something it should do at start up?

**Comment by DuckBoss** [comment]
> Not a big issue as it will rarely be restarted but it sounds like something it should do at start up?

Hello! This is actually an intended feature which needs a little bit of explaining.

1. When the bot starts up, it imports the command's permission if it doesn't already exist in the database.
This usually happens when the database is generated for the first time.
2. Whenever the bot is started up afterwards, it doesn't update the command permissions from the file without the `refreshpermissions` command. 
This is because if a user modified a command permission using the `setpermission <cmd_name> <permission_level>`  command, the database would be updated with the new permission but the csv file would not resulting in non-persistent database changes.
Due to this, the `refreshpermissions` command <b>must</b> be used when the csv file is updated.
3. custom user privileges, and custom aliases also function similarly, requiring the `refreshuserprivileges` and `refreshaliases` command.

**Comment by benwallacestock** [comment]
Ahh yep that is all fine thanks for clearing that up!

**Pull request merged**
