### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by kaminascripts**
Closes https://github.com/DuckBoss/JJMumbleBot/issues/258

# Why Docker?
Docker allows consistent environments and an easy way to run applications without installing project dependencies in your system(except docker)

Follow this steps to get the JJMummbleBot running

### Docker setup 
Follow this [link](https://docs.docker.com/engine/install/) to install Docker and this [link](https://docs.docker.com/compose/install/) to install docker-compose.

### Clone JJMumbleBot repository.
```
git clone https://github.com/DuckBoss/JJMumbleBot.git
```

### Build JJMumbleBot image
`sudo docker compose build`

### Run JJMumbleBot container 
There are 2 options depending on where is your mumble server:
- If your mumble host is on internet or you need to pass custom arguments:
`sudo docker-compose run bot python /app -ip <MUMBLE_SERVER_HOST> -port 64738 -superuser test_user`
- If your mumble host is in your local machine:
`sudo docker-compose run bot`

### Tips
- When code changes you have to **build** the docker image and **run** bot again
- Container Bot config folder is mounted in your local JJMumbleBot/cfg path so you can make changes directly, then your have to **run** again the container

I would use Docker to have it in production(serving to real users) or when someone wants to test your project with ease and without installing dependencies but I would not recommend this for development because each code change requires rebuild the project and takes too long, ~3minutes aprox. most of time is installing VLC. (I have an i7-6500 @ 2.50GHz).

> Update: after cache optimizations this also could be used for development.

@DuckBoss test it and tell me what you think ;-)

### CODE REVIEW

**Comment by DuckBoss** [comment]
Hi, thanks a lot for this. I will test this out and let you know how it goes!

**Comment by DuckBoss** [comment]
@kaminascripts 
Hi, I have a couple questions about Docker if you don't mind answering.
1) So, I managed to get build the image and get it running. Is there a way to view the contents of this built container?
2) Is there a way to share builds with the github repo so that each JJMumbleBot version has an available docker image for users?
3) As far as creating directories within the container that the bot requires, how do the paths work? Is it like /app/JJMumbleBot/my_new_directory?

I hope my questions are clear and I got the terminology right.
Thanks in advance.

**Comment by kaminascripts** [comment]
> 1. Is there a way to share builds with the github repo so that each JJMumbleBot version has an available docker image for users?

You can share the image creating a tar archive with SAVE command https://docs.docker.com/engine/reference/commandline/save/

You could get this automatically on each merge to master creating a github action that build, save and push it to the repo

> 2. As far as creating directories within the container that the bot requires, how do the paths work? Is it like /app/JJMumbleBot/my_new_directory?

No, it will be /app/my_new_directory, the root content of your repo is saved in the /app directory, but this directory could be renamed as the repo name if you want, i follow the best practices to create the Dockerfile https://docs.docker.com/develop/develop-images/dockerfile_best-practices/ thats why i use the /app instead of the repo name.

> 3. Would you happen to know how to run VLC in the docker container since VLC can't run be run as root? FFmpeg seems to work fine.

We could create another user in the Dockerfile and rebuild the image to solve that

> 4. Is there a way for a user to put the mumble certification .pem file into the container so the bot can authenticate itself on the server? (because the docker configs are currently setup to not use cert files)

Yes for sure, in this case the user could put the certificate in the local cfg folder, we could explain that in the guide.

**Comment by DuckBoss** [comment]
> > 1. Would you happen to know how to run VLC in the docker container since VLC can't run be run as root? FFmpeg seems to work fine.
> 
> We could create another user in the Dockerfile and rebuild the image to solve that

I'm working on this bit but I can't seem to figure it out since all the online resources handle this differently from one another.
Do you know how to add a non-root user to the dockerfile?
I tried: `USER my_user` but I just got the error:
```Error response from daemon: unable to find user my_user: no matching entries in passwd file```


> > 1. Is there a way for a user to put the mumble certification .pem file into the container so the bot can authenticate itself on the server? (because the docker configs are currently setup to not use cert files)
> 
> Yes for sure, in this case the user could put the certificate in the local cfg folder, we could explain that in the guide.

If I'm distributing built containers as per my 1st question in the previous comment, would this work?
Wouldn't the user need to rebuild if the files are changed?
I'm very much used to virtual machines and I'm trying to understand how it is actually distributed.

**Comment by joncolas** [comment]
It is my pleasure to help you with this.



> Error response from daemon: unable to find user my_user: no matching entries in passwd file

Ok, I will try to fix it ;-)

> If I'm distributing built containers as per my 1st question in the previous comment, would this work?

Here we could do one of this two options:
- The best option (more portable and perhaps the one that requires the most work from you) is to allow the bot to read the configuration from environment variables (maybe just putting the most important ones would be enough) and if the variable is not defined use the config file as default values. We could create this file in the templates directory, something like config_docker_template.ini, then edit Dockerfile to move that file to the cfg/config.ini to be packed when we built the image, this file can't be modified as it will be in the image and we will use it as default values. Finally, the user only will have to set the environment variables before executing the docker run command,

- Another option (less portable) could be explaining in a guide that the container reads config from a local folder on his system, so the user have to create the folder and download the config file from the repo before `docker-compose up/run`. To refresh config, the user only has to execute that command again.
 
> I wish the compiling didn't take ~20mins, but I guess that's expected from my very old intel xeon server.


P.D.: WOW. maybe the raspberry pi goes faster xD

I hope I have explained myself correctly

**Comment by kaminascripts** [comment]
It is my pleasure to help you with this.

> Error response from daemon: unable to find user my_user: no matching entries in passwd file

Ok, I will try to fix it ;-)

> If I'm distributing built containers as per my 1st question in the previous comment, would this work?

Here we could do one of this two options:

- The best option (more portable and perhaps the one that requires the most work from you) is to allow the bot to read the configuration from environment variables (maybe just putting the most important ones would be enough) and if the variable is not defined use the config file as default values. We could create this file in the templates directory, something like config_docker_template.ini, then edit Dockerfile to move that file to the cfg/config.ini to be packed when we built the image, this file can't be modified as it will be in the image and we will use it as default values. Finally, the user only will have to set the environment variables before executing the docker run command,

- Another option (less portable) could be explaining in a guide that the container reads config from a local folder on his system, so the user have to create the folder and download the config file from the repo before docker-compose up/run. To refresh config, the user only has to execute that command again.

> I wish the compiling didn't take ~20mins, but I guess that's expected from my very old intel xeon server.

P.D.: WOW. maybe the raspberry pi goes faster xD

I hope I have explained myself correctly

**Comment by kaminascripts** [comment]
VLC player should work right now ;-)
```
[JJMumbleBot(4.2.2).Command]:Commands Received: [test_user -> !link <a href="https://www.youtube.com/watch?v=8pT9zjt9eBQ">https://www.youtube.com/watch?v=8pT9zjt9eBQ</a>]
VLC media player 3.0.11 Vetinari (revision 3.0.11-0-gdc0c5ced72)
```

**Comment by DuckBoss** [comment]
> Another option (less portable) could be explaining in a guide that the container reads config from a local folder on his system, so the user have to create the folder and download the config file from the repo before docker-compose up/run. To refresh config, the user only has to execute that command again.

Thanks for your help, I think I'm going to have to go with this option since there are a lot of configurable settings in the config.ini file. I will try to work on this sometime this weekend and see what the best solution is. I'm wondering if I should expand the launch parameters of the bot to support all the config options so that users that want specific changes to the config can do so.

> VLC player should work right now ;-)

Awesome, thanks!

**Comment by DuckBoss** [comment]
Hi,
This is the solution I've come up with for config.ini setup in docker (and in general if users want).

### Launch Parameters Update
I'm making all the options in the config file available to be overridden with launch parameters.

For example, if the default channel is configured to be `Root` in the config file,
 - running the bot with `-defaultchannel custom_channel` launch parameter would allow the user to change the DefaultChannel config option to 'custom_channel'.
These config changes made in the launch parameters would be saved to the config.ini file so that changes are persistent across launches.

### Config File Setup For Docker
By making all the config file options available as launch parameters, it opens up the possibility of a `-docker` launch parameter.
This launch parameter can setup a minimal config file from a `config_docker_template.ini` file like you mentioned in an earlier comment. Since all the config options will be available as launch parameters, if a user wants to modify the generated minimal config, they can modify individual config options with the launch parameters.

For example:
- running the bot with `-docker -defaultchannel custom_channel` parameters would setup a minimal docker config.ini file with the DefaultChannel option set to 'custom_channel.

### Mumble Certificate Setup
As far as providing a mumble certificate `.pem` file for bots that will be connecting to servers that require certificates,
I was thinking of just generating it within the docker container with a command like:
```
openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout jjmumblebot.pem -out jjmumblebot.pem -subj "/CN=jjmumblebot"
```
This would make it a lot more portable as the user would not have to manually add any files to the docker container.

<hr>
So this is the solution I've come up with that I think would solve any potential problems with integrating Docker.<br>
It would also introduce some convenient and optional launch parameter features to non-docker users.

What do you think?

**Comment by kaminascripts** [comment]
> These config changes made in the launch parameters would be saved to the config.ini file so that changes are persistent across launches.

I do not know of any case in real life that has this type of behavior, I think that the bot interface never should change a configuration file, it makes usability difficult. I would use the bot interface parameters only to override the config.ini parameters, if one is not set fall back to the default value in that file.
Sorry if I didn't understand the idea, could you explain it with more detail ? what is the purpose/usecase ?

> - running the bot with -docker -defaultchannel custom_channel parameters would setup a minimal docker config.ini file with the DefaultChannel option set to 'custom_channel' if a config.ini file hasn't been preconfigured by the user.

After thinking on it I believe that having launch parameters, the `-docker` flag and config_docker_template.ini file are not necessary as we can pass them to the docker run command (at least in this first iteration).

About adding a `-generate` parameter i think is a great idea to ease bot setup when mumble-server authentication requires a certificate. :muscle: 

> It would also introduce some convenient and optional launch parameter features to non-docker users. 

I only would change the code to improve the bot interface like the parameter expansion you did to ease the setup/config, not for using docker. docker is a layer on top that will enable portability and shareability.

Apart of this, i am thinking in adding a mumble-server service in the docker compose, so users don't need to have mumble-server installed, they only will do docker-compose up, then a mumble-server container will be created and the bot will connect to it, the user will have the possibility to run the bot only, without the mumble server. What do you think of this? With this we will cover the text message setting in the mumble-server.

**Comment by DuckBoss** [comment]
> > These config changes made in the launch parameters would be saved to the config.ini file so that changes are persistent across launches.
> 
> I do not know of any case in real life that has this type of behavior, I think that the bot interface never should change a configuration file, it makes usability difficult. I would use the bot interface parameters only to override the config.ini parameters, if one is not set fall back to the default value in that file.
> Sorry if I didn't understand the idea, could you explain it with more detail ? what is the purpose/usecase ?

Sorry about the confusion, I think I just wrote the wrong thing because it **does not** save the launch parameters to the config.ini file. Using the launch parameters will not make any changes to the config.ini file. As you said, it will only override the config.ini parameters and fallback to the values in the config.ini file if a launch parameter is not provided.

I'm not quite sure why I wrote it that way, sorry about that!

> > * running the bot with -docker -defaultchannel custom_channel parameters would setup a minimal docker config.ini file with the DefaultChannel option set to 'custom_channel' if a config.ini file hasn't been preconfigured by the user.
> 
> After thinking on it I believe that having launch parameters, the `-docker` flag and config_docker_template.ini file are not necessary as we can pass them to the docker run command (at least in this first iteration).

Could you expand on how this can be passed to the docker run command?
From my understanding the user would copy the docker_template_config.ini file and make required changes for the bot to use,
and any optional launch parameters that the bot supports would override the config file parameters.

I've tested the bot with a `-docker` parameter (all it does is copy the docker_template_config.ini and sets it up to be the main config file with a minimal setup), but if your suggestion works I would prefer that!

> > It would also introduce some convenient and optional launch parameter features to non-docker users.
> 
> I only would change the code to improve the bot interface like the parameter expansion you did to ease the setup/config, not for using docker. docker is a layer on top that will enable portability and shareability.

Yes, you're right. I've currently updated my code to expand the launch parameters to include all the options in the config file.
Changes can be made as necessary.

> Apart of this, i am thinking in adding a mumble-server service in the docker compose, so users don't need to have mumble-server installed, they only will do docker-compose up, then a mumble-server container will be created and the bot will connect to it, the user will have the possibility to run the bot only, without the mumble server. What do you think of this? With this we will cover the text message setting in the mumble-server.

That sounds like a great idea! I have no idea how to go about setting up the docker-compose though.

**Comment by kaminascripts** [comment]
> Could you expand on how this can be passed to the docker run command?
> From my understanding the user would copy the docker_template_config.ini file and make required changes for the bot to use,
> and any optional launch parameters that the bot supports would override the config file parameters.

We will move the cfg/templates/config_template.ini to cfg/config.ini in the Dockerfile, then we have two options to run the container.
```
sudo docker run --rm --name jjmumblebot --network host -it jjmumblebot_bot:latest python /app -ip 127.0.0.1 -port 64738
```
or
```
sudo docker-compose run bot python /app -ip 127.0.0.1 -port 64738
```
or via [command in docker-compose.yaml](https://github.com/DuckBoss/JJMumbleBot/pull/265/files#diff-eb672b1ddd3aa7dae5f2577f38daa271R10)

I would like to test this with your changes about the parameter expansion, when they will be available?

**Comment by DuckBoss** [comment]
I've pushed the updates to the dockerize_bot branch.

Here's the patch notes:

###  Added many launch parameters and fixed some bugs
- Added all config options to the launch parameters.
- Added -generatecert launch parameter to generate certs.
- Added openssl to the DockerFile apt-get (for cert generation)
- Updated core bot_service.py to create missing directories.
- Renamed some string references.
- Fixed audio library bugs with the media/sound_board plugins.
- Added 'MaxLogSize' option to the config_template.ini file
- Fixed some errors that occurred when commands weren't formatted properly.
- Fixed logging issue in whisper plugin.

**Comment by kaminascripts** [comment]
> I've also disabled Logging in the config_template.ini by default because the bot isn't able to create the runtimelog.log file due to a permission denied error in docker builds.

I think the code should create the Logging folder when Logging is defined.

**Comment by kaminascripts** [comment]
- The local directory is no longer mounted in the container's config because now we the config as default (when bot is executed you moved it from cfg/templates_config.ini to cfg/config.ini).

- Also now the docker-compose parameters are being overrided (not `python /app`, only parameters) when are passed to `docker-compose run bot`. It works like this:

  1. Without parameters:
    ```
    sudo docker-compose run bot
    ```
    In this case the user connected to the mumble client does not have rights to execute any command
    ```
    [JJMumbleBot(4.3.0).Command]:Commands Received: [test_user -> !link <a href="https://www.youtube.com/watch?v=-9MEZU6lOuU">https://www.youtube.com/watch?v=-9MEZU6lOuU</a>]
    [JJMumbleBot(4.3.0).General]:User [test_user] does not have the user privileges to use this command: [link]
    ```
1. Overriding parameters:
    ```
    sudo docker-compose run bot -ip 127.0.0.1 -port 64738 -superuser test_user
    ```
    When we have to pass any new additional parameter like `-superuser` we have to pass all parameters to docker-compose


- I tested the web interface, I tried `!link` command but it gave me this error:

```
[JJMumbleBot(4.3.0).Command]:Commands Received: [JJMumbleBot -> !link https://www.youtube.com/watch?v=-9MEZU6lOuU]
[JJMumbleBot(4.3.0).General]:User [JJMumbleBot] does not have the user privileges to use this command: [link]

```

**Comment by kaminascripts** [comment]
Maybe we should mount a local folder for the .db file, don't you think? So we don't lose the state of the bot

**Comment by DuckBoss** [comment]
> > I've also disabled Logging in the config_template.ini by default because the bot isn't able to create the runtimelog.log file due to a permission denied error in docker builds.
> 
> I think the code should create the Logging folder when Logging is defined.

I managed to fix this in the code. The problem was that it was trying to create the log in whatever the docker container's root directory was instead of the main directory of the bot, which caused  file permission errors.
This has been fixed now

**Comment by DuckBoss** [comment]
> * I tested the web interface, I tried `!link` command but it gave me this error:
>   ```
>   [JJMumbleBot(4.3.0).Command]:Commands Received: [JJMumbleBot -> !link https://www.youtube.com/watch?v=-9MEZU6lOuU]
>   [JJMumbleBot(4.3.0).General]:User [JJMumbleBot] does not have the user privileges to use this command: [link]
>   ```

In the quick start guide on the wiki, it states that the bot username  has to be given super user privileges in the database to execute commands from the web interface.
I have made an update to make this automatic, So the bot should add itself to the user privileges if the web interface is enabled. I've tested the web interface now and it seems to be working fine.

**Comment by DuckBoss** [comment]
> Maybe we should mount a local folder for the .db file, don't you think? So we don't lose the state of the bot

Yes, this should definitely be added. It would also be required for users that have certificates for their bot clients already registered to the server (so they won't generate a new one with the bot).

**Comment by DuckBoss** [comment]
> * The local directory is no longer mounted in the container's config because now we are using the config as default (when bot is executed you moved it from cfg/templates_config.ini to cfg/config.ini).

I think this commit should be reverted because the bot only moves the cfg/config_template.ini to cfg/config.ini if the config.ini file doesn't already exist. Users that already have a config.ini file would only have to put their config in the local cfg folder for it to work.
Removing the local cfg mount would be detrimental to users that already have config/database/aliases files.

> Maybe we should mount a local folder for the .db file, don't you think? So we don't lose the state of the bot

It would also allow database and aliases files to be persistent as mentioned here ^

<hr>

Am I correct in assuming this is how it works, or am I missing something?

**Comment by kaminascripts** [comment]
Maybe we have to move JJMumbleBot/cfg/templates to other dir because we mount cfg dir only to load custom config.ini, aliases and save database, not templates.

One question, how is generated the database name? Does it depend on the bot name?

**Comment by DuckBoss** [comment]
> Maybe we have to move JJMumbleBot/cfg/templates to other dir because we mount cfg dir only to load custom config.ini, aliases and save database, not templates.

Yes, we could  do that. A bunch of references will need to be updated first because it looks for template files within /cfg/templates/.

> One question, how is generated the database name? Does it depend on the bot name?

The database is generated as 'jjmumblebot.db'. It doesn't change names depending on the bot name.
If database backups are enabled in the config, it will  store periodic backups of this database in /cfg/backups/

**Comment by DuckBoss** [comment]
> > Maybe we have to move JJMumbleBot/cfg/templates to other dir because we mount cfg dir only to load custom config.ini, aliases and save database, not templates.
> 
> Yes, we could do that. A bunch of references will need to be updated first because it looks for template files within /cfg/templates/.

I've moved templates folder from `JJMumbleBot/cfg/templates` to `JJMumbleBot/templates/` in the most recent commit: https://github.com/DuckBoss/JJMumbleBot/pull/265/commits/410d8d4c4888605c06cf2b3deb0836cb935e6ede

**Comment by kaminascripts** [comment]
About where we store the image, what you prefer ?
- Upload the image to the official docker [DockerHub](https://hub.docker.com/search?q=&type=image). Docker Hub is the world's largest
library and community for container images.
- Upload the image to your JJMumbleBot repository

I've never done one of these but I think its trivial. I only have used [AWS ECR](https://aws.amazon.com/es/ecr/) for work (pricing  is 0,10 USD per GB/month)

**Comment by DuckBoss** [comment]
I was thinking of doing both DockerHub and Github releases to be honest.
I think using Github Actions, it can automatically build and push to DockerHub.
Then there is probably another Github Action that can use the docker save command for tar archives.

I've never done this before, do you think it's possible?

**Comment by kaminascripts** [comment]
> I was thinking of doing both DockerHub and Github releases to be honest.
> I think using Github Actions, it can automatically build and push to DockerHub.
> I think initially, just working on the Github Action to build/push to DockerHub and worry about tar archives later if needed.
> I've never done this before, do you think it's possible?

Sure! i have done many github actions i could help you if you want.

> Also, is there any more work that needs to be done or is this ready to merge to the master branch? My plan is to work on automatically build/push the image to DockerHub (and it seems that DockerHub has this feature). Then, all the documentation needs to be updated and some final testing before releasing as a part of v4.3.0 

Ok, I keep working in a way to add mumble-server service in docker compose, but I will add it later, it's taking me longer. If you don't have more changes to do, can i merge this PR ?

**Comment by kaminascripts** [comment]
Could you test this command?
```
!sbdownload https://www.youtube.com/watch?v=TxUmzblpvf0 test 0:0:5-0:0:15
```
Bot logs:
```
[JJMumbleBot(4.3.0).Command]:Commands Received: [test_user -> !link <a href="https://www.youtube.com/watch?v=TxUmzblpvf0">https://www.youtube.com/watch?v=TxUmzblpvf0</a>]
VLC media player 3.0.11 Vetinari (revision 3.0.11-0-gdc0c5ced72)
[JJMumbleBot(4.3.0).Command]:Commands Received: [test_user -> !stop]
[JJMumbleBot(4.3.0).Command]:Commands Received: [test_user -> !help]
[JJMumbleBot(4.3.0).Command]:Commands Received: [test_user -> !help sound_board]
[JJMumbleBot(4.3.0).Command]:Commands Received: [test_user -> !sbdownload <a href="https://www.youtube.com/watch?v=TxUmzblpvf0">https://www.youtube.com/watch?v=TxUmzblpvf0</a> test 0:0:5-0:0:15]
Removing cache dir /root/.cache/youtube-dl ...
[youtube] TxUmzblpvf0: Downloading webpage
[youtube] Downloading just video TxUmzblpvf0 because of --no-playlist
[youtube] TxUmzblpvf0: Downloading js player 4b1ba5ea
[youtube] TxUmzblpvf0: Downloading js player 4b1ba5ea
Input #0, matroska,webm, from 'https://r4---sn-8vq54voxn25po-h5qd.googlevideo.com/videoplayback?expire=1600835514&ei=WntqX83wFIX4xwLV8o-IAg&ip=62.42.82.169&id=o-AKWr3XOD8B6UMNtN-0wdcWNhGkDAZ7qaA4RK0J25FuSr&itag=251&source=youtube&requiressl=yes&mh=lU&mm=31%2C29&mn=sn-8vq54voxn25po-h5qd%2Csn-h5q7knes&ms=au%2Crdu&mv=m&mvi=4&pl=23&gcr=es&initcwndbps=1073750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=3863333&dur=228.421&lmt=1599491107694368&mt=1600813832&fvip=4&keepalive=yes&fexp=23915655&c=WEB&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALKuDX7IpINpPE6NfJT5z4LBROBOhZ_Cv4HDiUguhGCtAiAJR92hmFjQeKjfZzcV-Z2kZkaO-DU65DsIdGkGwON-DQ%3D%3D&sig=AOq0QJ8wRAIgJBnklJ2ssOHqXM0zgzjQ8XQP-fmIfQ1EtgfjIlBEVDsCICzPqgwDJXzQcDooalMczH60NKPSgJPn8YYnRH1DDG9R&ratebypass=yes':
  Metadata:
    encoder         : google/video-file
  Duration: 00:03:48.42, start: -0.007000, bitrate: 135 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, ogg, to '/app/JJMumbleBot/cfg/permanent_media_directory/sound_board/test.ogg':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      encoder         : Lavf58.20.100
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=     257kB time=00:00:09.98 bitrate= 210.7kbits/s speed= 125x    
video:0kB audio:255kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.789512%
[JJMumbleBot(4.3.0).Command]:Commands Received: [test_user -> !sb test]
```
i checked that test.ogg was succesfully downloaded and I can play it without problems from my local VLC but from mumble client it says `Now playing[File(-1)]: test by test_user` but i can't hear anything. I tested before a youtube song with `!link` to check that the bot can play sounds.

Any ideas?

**Comment by DuckBoss** [comment]
image
I've set up automated builds in DockerHub, I'm assuming once we merge the PR we won't need  a Github Action to push to docker, correct?

<hr>

I'll check the `!sbdownload` command before merging the PR, It seems like some youtube videos encounter a codec problem with ffmpeg and other youtube videos are able to download/trim  just fine.

**Comment by kaminascripts** [comment]
> I've set up automated builds in DockerHub, I'm assuming once we merge the PR we won't need a Github Action to push to docker, correct?

Thats right, it seems DockerHub doesn't need GitHub actions as they already have a GitHub integration

> Worst case scenario if this occurs very often, I might be able to fix this by having ffmpeg download the full video, and then trim it instead of trimming it directly while downloading.

Thank you very much I will have it on mind.

**Comment by kaminascripts** [comment]
Can we merge this ?

**Comment by DuckBoss** [comment]
> Ok, I keep working in a way to add mumble-server service in docker compose, but I will add it later, it's taking me longer. If you don't have more changes to do, can i merge this PR ?

I'm going to merge this PR, and test it around a bit before releasing it in v4.3.0
We can add the mumble-server service after merging this PR since it is an additional feature.

**Pull request merged**
